name: CI

on:
  push:
    branches:
      - '*'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

concurrency:
  # On master/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/release' ) && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  matrix_prep:
    name: Matrix Preparation
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - id: set-matrix
        run: |
          node .github/workflows/matrix.js

  test:
    needs: matrix_prep
    name: '${{ matrix.name }}'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50
    
    - name: Set up Java 17 
      uses: actions/setup-java@v4
      with:
        # The latest one will be the default, so we use Java 17 for launching Gradle
        java-version: |
          17
        distribution: temurin
        architecture: s390x
    - name: Steps to reproduce
      uses: actions/github-script@v7
      with:
        script: |
          console.log('The following command might help reproducing CI results, use Java ${{ matrix.java_version }}')
          console.log('TZ="${{ matrix.tz }}" _JAVA_OPTIONS="${{ matrix.extraJvmArgs }}" ./gradlew build -x distTar -x distTarSource -x distTarSha512 -x distTarSourceSha512 ${{ matrix.extraGradleArgs }} -PtestExtraJvmArgs="${{ matrix.testExtraJvmArgs }}" -PtestDisableCaching="${{ matrix.testDisableCaching }}"')
    - name: Test
      shell: bash
      run: |
        ./gradlew --scan --no-parallel build -x distTar -x distTarSource -x distTarSha512 -x distTarSourceSha512 -PtestExtraJvmArgs=${{ matrix.testExtraJvmArgs }} -PtestDisableCaching=${{ matrix.testDisableCaching }}
      
  errorprone:
    name: 'Error Prone (JDK 17)'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: 'Test'
      run: |
        ./gradlew --no-parallel build -Dskip.test_TestDNSCacheManager.testWithCustomResolverAnd1Server=true -Djava.awt.headless=true -PjdkBuildVersion=17
      env:
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
